In [4]:
import torch

In [5]:
class DenseLayer:
  def __init__(self,n_features,n_neurons):
    self.weights = 0.01 * torch.rand(n_neurons,n_features)
    self.bias = torch.zeros((1,n_neurons))
  def forward(self, inputs):
    self.output = torch.matmul(inputs,self.weights.T) + self.bias

In [6]:
input = torch.rand(32,5)
input, input.size()

(tensor([[0.5270, 0.9539, 0.3400, 0.3309, 0.6115],
         [0.9643, 0.1605, 0.6071, 0.2657, 0.9237],
         [0.4650, 0.2974, 0.1894, 0.8249, 0.3777],
         [0.5015, 0.0538, 0.9945, 0.3260, 0.0195],
         [0.9161, 0.7830, 0.0118, 0.1952, 0.7121],
         [0.5883, 0.2685, 0.3494, 0.9367, 0.6620],
         [0.3740, 0.7682, 0.4073, 0.8196, 0.4784],
         [0.0210, 0.8835, 0.4296, 0.7104, 0.6727],
         [0.4440, 0.2519, 0.4646, 0.4196, 0.7978],
         [0.1077, 0.6555, 0.4536, 0.4334, 0.2027],
         [0.8684, 0.5069, 0.4052, 0.5445, 0.4120],
         [0.9815, 0.0146, 0.0698, 0.3951, 0.7769],
         [0.0320, 0.5275, 0.9749, 0.6633, 0.4951],
         [0.9144, 0.5427, 0.2126, 0.8782, 0.0610],
         [0.1719, 0.5461, 0.0878, 0.4048, 0.3283],
         [0.6546, 0.5478, 0.6194, 0.2279, 0.5372],
         [0.3825, 0.5039, 0.2717, 0.2088, 0.9112],
         [0.9929, 0.8904, 0.4089, 0.2296, 0.9488],
         [0.5219, 0.8793, 0.9679, 0.3723, 0.4500],
         [0.6168, 0.7338, 0.303

In [7]:
first_layer = DenseLayer(5,16)
first_layer.forward(input)

first_layer.output


tensor([[0.0191, 0.0169, 0.0152, 0.0130, 0.0116, 0.0167, 0.0128, 0.0097, 0.0197,
         0.0135, 0.0108, 0.0128, 0.0144, 0.0172, 0.0124, 0.0207],
        [0.0158, 0.0155, 0.0161, 0.0133, 0.0176, 0.0189, 0.0171, 0.0125, 0.0186,
         0.0159, 0.0139, 0.0114, 0.0149, 0.0133, 0.0154, 0.0238],
        [0.0153, 0.0135, 0.0112, 0.0084, 0.0123, 0.0131, 0.0139, 0.0125, 0.0130,
         0.0140, 0.0096, 0.0069, 0.0081, 0.0147, 0.0116, 0.0173],
        [0.0101, 0.0103, 0.0091, 0.0122, 0.0151, 0.0116, 0.0145, 0.0077, 0.0135,
         0.0076, 0.0116, 0.0081, 0.0128, 0.0096, 0.0080, 0.0166],
        [0.0180, 0.0139, 0.0151, 0.0105, 0.0101, 0.0169, 0.0129, 0.0112, 0.0174,
         0.0150, 0.0105, 0.0134, 0.0131, 0.0150, 0.0150, 0.0196],
        [0.0185, 0.0175, 0.0147, 0.0112, 0.0167, 0.0172, 0.0175, 0.0152, 0.0170,
         0.0176, 0.0124, 0.0083, 0.0108, 0.0176, 0.0145, 0.0227],
        [0.0204, 0.0187, 0.0148, 0.0129, 0.0144, 0.0167, 0.0156, 0.0126, 0.0193,
         0.0154, 0.0117, 0.0105, 0.01

In [8]:
second_layer = DenseLayer(16,16)
second_layer.forward(first_layer.output)

second_layer.output

tensor([[0.0011, 0.0009, 0.0012, 0.0016, 0.0012, 0.0009, 0.0011, 0.0012, 0.0011,
         0.0012, 0.0013, 0.0013, 0.0011, 0.0013, 0.0011, 0.0011],
        [0.0012, 0.0009, 0.0013, 0.0018, 0.0013, 0.0009, 0.0012, 0.0012, 0.0011,
         0.0013, 0.0014, 0.0013, 0.0012, 0.0014, 0.0012, 0.0012],
        [0.0009, 0.0007, 0.0010, 0.0013, 0.0010, 0.0007, 0.0009, 0.0010, 0.0009,
         0.0010, 0.0011, 0.0011, 0.0009, 0.0011, 0.0009, 0.0010],
        [0.0008, 0.0006, 0.0010, 0.0012, 0.0009, 0.0006, 0.0009, 0.0009, 0.0008,
         0.0009, 0.0010, 0.0009, 0.0008, 0.0010, 0.0008, 0.0008],
        [0.0011, 0.0008, 0.0012, 0.0016, 0.0012, 0.0008, 0.0011, 0.0011, 0.0010,
         0.0012, 0.0013, 0.0012, 0.0011, 0.0013, 0.0010, 0.0011],
        [0.0012, 0.0009, 0.0013, 0.0017, 0.0013, 0.0009, 0.0012, 0.0012, 0.0011,
         0.0013, 0.0014, 0.0013, 0.0011, 0.0014, 0.0011, 0.0013],
        [0.0012, 0.0009, 0.0013, 0.0017, 0.0013, 0.0009, 0.0012, 0.0012, 0.0011,
         0.0013, 0.0014, 0.0014, 0.00

In [9]:
third_layer = DenseLayer(16,16)
third_layer.forward(second_layer.output)

third_layer.output

tensor([[8.6929e-05, 9.1896e-05, 9.8122e-05, 7.2379e-05, 1.1204e-04, 9.0874e-05,
         1.0954e-04, 8.5741e-05, 1.0685e-04, 1.1250e-04, 8.3146e-05, 9.6008e-05,
         9.0851e-05, 8.5436e-05, 9.7976e-05, 6.4883e-05],
        [9.4109e-05, 9.8978e-05, 1.0598e-04, 7.8233e-05, 1.2063e-04, 9.8352e-05,
         1.1815e-04, 9.2461e-05, 1.1518e-04, 1.2118e-04, 9.0008e-05, 1.0330e-04,
         9.8096e-05, 9.2398e-05, 1.0541e-04, 6.9746e-05],
        [7.2105e-05, 7.6090e-05, 8.1920e-05, 5.9864e-05, 9.2949e-05, 7.5059e-05,
         9.0665e-05, 7.0647e-05, 8.9099e-05, 9.2822e-05, 6.9331e-05, 8.0029e-05,
         7.5273e-05, 7.1510e-05, 8.1610e-05, 5.3884e-05],
        [6.5394e-05, 6.8695e-05, 7.3139e-05, 5.4126e-05, 8.3896e-05, 6.8542e-05,
         8.2110e-05, 6.4323e-05, 7.9946e-05, 8.4369e-05, 6.2642e-05, 7.1323e-05,
         6.8513e-05, 6.3921e-05, 7.3146e-05, 4.8102e-05],
        [8.4590e-05, 8.8993e-05, 9.5373e-05, 7.0451e-05, 1.0858e-04, 8.8223e-05,
         1.0608e-04, 8.2992e-05, 1.0351

In [10]:
output = DenseLayer(16,5)
output.forward(third_layer.output)

output.output

tensor([[7.7622e-06, 8.9325e-06, 6.7923e-06, 8.7271e-06, 8.2293e-06],
        [8.3675e-06, 9.6330e-06, 7.3262e-06, 9.4132e-06, 8.8807e-06],
        [6.4453e-06, 7.4168e-06, 5.6412e-06, 7.2405e-06, 6.8373e-06],
        [5.8082e-06, 6.6895e-06, 5.0806e-06, 6.5328e-06, 6.1619e-06],
        [7.5225e-06, 8.6573e-06, 6.5874e-06, 8.4640e-06, 7.9836e-06],
        [8.2195e-06, 9.4588e-06, 7.1941e-06, 9.2342e-06, 8.7187e-06],
        [8.2071e-06, 9.4437e-06, 7.1802e-06, 9.2197e-06, 8.6996e-06],
        [7.3995e-06, 8.5126e-06, 6.4712e-06, 8.3076e-06, 7.8361e-06],
        [6.6093e-06, 7.6066e-06, 5.7844e-06, 7.4281e-06, 7.0084e-06],
        [5.2598e-06, 6.0527e-06, 4.5994e-06, 5.9086e-06, 5.5720e-06],
        [8.2060e-06, 9.4458e-06, 7.1833e-06, 9.2288e-06, 8.7085e-06],
        [6.6255e-06, 7.6264e-06, 5.8045e-06, 7.4537e-06, 7.0375e-06],
        [7.4820e-06, 8.6110e-06, 6.5416e-06, 8.4022e-06, 7.9243e-06],
        [8.2522e-06, 9.4983e-06, 7.2240e-06, 9.2785e-06, 8.7601e-06],
        [4.3355e-06,